
package net.mail.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MyOwnMailAgent", targetNamespace = "http://service.ws.mail.net/", wsdlLocation = "http://localhost:8080/gmailws/services/concat?wsdl")
public class MyOwnMailAgent
    extends Service
{

    private final static URL MYOWNMAILAGENT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.mail.ws.client.MyOwnMailAgent.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.mail.ws.client.MyOwnMailAgent.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/gmailws/services/concat?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/gmailws/services/concat?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MYOWNMAILAGENT_WSDL_LOCATION = url;
    }

    public MyOwnMailAgent(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyOwnMailAgent() {
        super(MYOWNMAILAGENT_WSDL_LOCATION, new QName("http://service.ws.mail.net/", "MyOwnMailAgent"));
    }

    /**
     * 
     * @return
     *     returns WSMail
     */
    @WebEndpoint(name = "WSMailImplPort")
    public WSMail getWSMailImplPort() {
        return super.getPort(new QName("http://service.ws.mail.net/", "WSMailImplPort"), WSMail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMail
     */
    @WebEndpoint(name = "WSMailImplPort")
    public WSMail getWSMailImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.mail.net/", "WSMailImplPort"), WSMail.class, features);
    }

}
