
package net.mail.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSMail", targetNamespace = "http://david.bromberg.fr/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSMail {


    /**
     * 
     * @param password
     * @param smtpHost
     * @param smtpPort
     * @param from
     * @param to
     * @param username
     * @param isSSL
     */
    @WebMethod
    public void sendMail(
        @WebParam(name = "smtpHost", partName = "smtpHost")
        String smtpHost,
        @WebParam(name = "smtpPort", partName = "smtpPort")
        int smtpPort,
        @WebParam(name = "from", partName = "from")
        String from,
        @WebParam(name = "to", partName = "to")
        String to,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "isSSL", partName = "isSSL")
        boolean isSSL);

}
