//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 12:10:33 AM ICT 
//


package net.serialisation.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.serialisation.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CatalogData_QNAME = new QName("", "CatalogData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.serialisation.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CatalogDataType }
     * 
     */
    public CatalogDataType createCatalogDataType() {
        return new CatalogDataType();
    }

    /**
     * Create an instance of {@link Booksdata }
     * 
     */
    public Booksdata createBooksdata() {
        return new Booksdata();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatalogDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CatalogData")
    public JAXBElement<CatalogDataType> createCatalogData(CatalogDataType value) {
        return new JAXBElement<CatalogDataType>(_CatalogData_QNAME, CatalogDataType.class, null, value);
    }

}
