//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.31 at 10:44:15 PM ICT 
//


package net.flickr.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.flickr.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Rsp_QNAME = new QName("", "rsp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.flickr.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PhotoType }
     * 
     */
    public PhotoType createPhotoType() {
        return new PhotoType();
    }

    /**
     * Create an instance of {@link PhotosType }
     * 
     */
    public PhotosType createPhotosType() {
        return new PhotosType();
    }

    /**
     * Create an instance of {@link ErrType }
     * 
     */
    public ErrType createErrType() {
        return new ErrType();
    }

    /**
     * Create an instance of {@link RspType }
     * 
     */
    public RspType createRspType() {
        return new RspType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RspType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rsp")
    public JAXBElement<RspType> createRsp(RspType value) {
        return new JAXBElement<RspType>(_Rsp_QNAME, RspType.class, null, value);
    }

}
